version: "3.8"

services:
  backend:
    build:
      context: ./product-catalog-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev

  frontend:
    build:
      context: ./product-catalog-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./product-catalog-frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend
