version: "3.8"

services:
  backend:
    build:
      context: ./product-catalog-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev

  frontend:
    build:
      context: ./product-catalog-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
